#!/usr/bin/env ruby

source_root=File.expand_path('~/tools/git-hooks')
pre_push_hook='pre_push/is_remote_updated'
source_path=File.join(source_root, pre_push_hook)

target1_root=File.expand_path('~/tools/test-git/local-push/client1')
target2_root=File.expand_path('~/tools/test-git/local-push/client2')
hook_location='.git/hooks'
hook_name='pre-push'
target1_path=File.join(target1_root, hook_location, hook_name)
target2_path=File.join(target2_root, hook_location, hook_name)

if ARGV[0] == 'i'
  puts 'install!'
  if (File.symlink?(target1_path) == false)
    puts 'symlink not exists'
    File.symlink(source_path, target1_path) #mode is set as 0755 by default. no need to execute File.chmod
  else
    puts 'symlink already exists'
  end
elsif ARGV[0] == 'u'
  puts 'uninstall!'
  puts "there exists symlink to remove" if File.symlink?(target1_path)
  File.delete(target1_path) if File.symlink?(target1_path)
end
